"""empty message

Revision ID: 7564357e2e0b
Revises: 057a987cc285
Create Date: 2018-04-20 13:32:18.577811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7564357e2e0b'
down_revision = '057a987cc285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clap',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_clap_timestamp'), 'clap', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clap_timestamp'), table_name='clap')
    op.drop_table('clap')
    # ### end Alembic commands ###
